# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52c0761fc23f98c30ed3d9dbf7bddb6801c6cc678c2558b2281ee79e4d38b0409326113b921a05cf36613eae30c98ac1f897d85a36402135d657e25d336db386

test:
  secret_key_base: 4e743943e4fcc26158c8fdf22d3b1a217093f23dc6374b675ca1393e4dddcf1fd7f8fa8a777b645d0a6f2a14a18e498a8e1b5f312debd77f578cfc7c18e42c11

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
